{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectionErrors"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/SingleConnectionFailure","preciseIdentifier":"s:3NIO23SingleConnectionFailureV","text":"SingleConnectionFailure"},{"kind":"text","text":"] { get }"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/nio\/nioconnectionerror\/connectionerrors"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.swift.docc\/documentation\/NIO\/NIOConnectionError\/connectionErrors","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The errors we encountered during the connection attempts."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectionErrors"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SingleConnectionFailure","preciseIdentifier":"s:3NIO23SingleConnectionFailureV"},{"kind":"text","text":"]"}],"title":"connectionErrors","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:3NIO18NIOConnectionErrorV16connectionErrorsSayAA23SingleConnectionFailureVGvp","modules":[{"name":"NIO"}]},"hierarchy":{"paths":[["doc:\/\/org.swift.docc\/documentation\/NIO","doc:\/\/org.swift.docc\/documentation\/NIO\/NIOConnectionError"]]},"references":{"doc://org.swift.docc/documentation/NIO/NIOConnectionError":{"role":"symbol","title":"NIOConnectionError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"NIOConnectionError"}],"abstract":[{"type":"text","text":"A representation of all the errors that happened during an attempt to connect"},{"type":"text","text":" "},{"type":"text","text":"to a given host and port."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/NIOConnectionError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NIOConnectionError"}],"url":"\/documentation\/nio\/nioconnectionerror"},"doc://org.swift.docc/documentation/NIO/SingleConnectionFailure":{"role":"symbol","title":"SingleConnectionFailure","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SingleConnectionFailure"}],"abstract":[{"type":"text","text":"An error that occurred during connection to a given target."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/SingleConnectionFailure","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SingleConnectionFailure"}],"url":"\/documentation\/nio\/singleconnectionfailure"},"doc://org.swift.docc/documentation/NIO":{"role":"collection","title":"NIO","abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO","kind":"symbol","type":"topic","url":"\/documentation\/nio"},"doc://org.swift.docc/documentation/NIO/NIOConnectionError/connectionErrors":{"role":"symbol","title":"connectionErrors","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectionErrors"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SingleConnectionFailure","preciseIdentifier":"s:3NIO23SingleConnectionFailureV"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"The errors we encountered during the connection attempts."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/NIOConnectionError\/connectionErrors","kind":"symbol","type":"topic","url":"\/documentation\/nio\/nioconnectionerror\/connectionerrors"}}}