{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cascadeFailure"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"NewValue"},{"kind":"text","text":">("},{"kind":"externalParam","text":"to"},{"kind":"text","text":" "},{"kind":"internalParam","text":"promise"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/EventLoopPromise","preciseIdentifier":"s:3NIO16EventLoopPromiseV","text":"EventLoopPromise"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"NewValue","preciseIdentifier":"s:3NIO15EventLoopFutureC14cascadeFailure2toyAA0bC7PromiseVyqd__GSg_tlF8NewValueL_qd__mfp"},{"kind":"text","text":">?)"}],"languages":["swift"],"platforms":["macOS"]}]},{"kind":"parameters","parameters":[{"name":"to","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"EventLoopPromise"},{"type":"text","text":" that should fail with the error of this "},{"type":"codeVoice","code":"EventLoopFuture"},{"type":"text","text":"."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This is an alternative variant of "},{"type":"codeVoice","code":"cascade"},{"type":"text","text":" that allows you to potentially return early failures in"},{"type":"text","text":" "},{"type":"text","text":"error cases, while passing the user "},{"type":"codeVoice","code":"EventLoopPromise"},{"type":"text","text":" onwards."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/nio\/eventloopfuture\/cascadefailure(to:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.swift.docc\/documentation\/NIO\/EventLoopFuture\/cascadeFailure(to:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Fails the given "},{"type":"codeVoice","code":"EventLoopPromise"},{"type":"text","text":" with the error from this "},{"type":"codeVoice","code":"EventLoopFuture"},{"type":"text","text":" if encountered."}],"kind":"symbol","metadata":{"role":"symbol","title":"cascadeFailure(to:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cascadeFailure"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"NewValue"},{"kind":"text","text":">("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EventLoopPromise","preciseIdentifier":"s:3NIO16EventLoopPromiseV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"NewValue","preciseIdentifier":"s:3NIO15EventLoopFutureC14cascadeFailure2toyAA0bC7PromiseVyqd__GSg_tlF8NewValueL_qd__mfp"},{"kind":"text","text":">?)"}],"symbolKind":"method","externalID":"s:3NIO15EventLoopFutureC14cascadeFailure2toyAA0bC7PromiseVyqd__GSg_tlF","extendedModule":"NIO","modules":[{"name":"NIO"}]},"hierarchy":{"paths":[["doc:\/\/org.swift.docc\/documentation\/NIO","doc:\/\/org.swift.docc\/documentation\/NIO\/EventLoopFuture"]]},"references":{"doc://org.swift.docc/documentation/NIO/EventLoopFuture/cascadeFailure(to:)":{"role":"symbol","title":"cascadeFailure(to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cascadeFailure"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"NewValue"},{"kind":"text","text":">("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EventLoopPromise","preciseIdentifier":"s:3NIO16EventLoopPromiseV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"NewValue","preciseIdentifier":"s:3NIO15EventLoopFutureC14cascadeFailure2toyAA0bC7PromiseVyqd__GSg_tlF8NewValueL_qd__mfp"},{"kind":"text","text":">?)"}],"abstract":[{"type":"text","text":"Fails the given "},{"type":"codeVoice","code":"EventLoopPromise"},{"type":"text","text":" with the error from this "},{"type":"codeVoice","code":"EventLoopFuture"},{"type":"text","text":" if encountered."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/EventLoopFuture\/cascadeFailure(to:)","kind":"symbol","type":"topic","url":"\/documentation\/nio\/eventloopfuture\/cascadefailure(to:)"},"doc://org.swift.docc/documentation/NIO/EventLoopFuture":{"role":"symbol","title":"EventLoopFuture","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EventLoopFuture"}],"abstract":[{"type":"text","text":"Holder for a result that will be provided later."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/EventLoopFuture","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EventLoopFuture"}],"url":"\/documentation\/nio\/eventloopfuture"},"doc://org.swift.docc/documentation/NIO/EventLoopPromise":{"role":"symbol","title":"EventLoopPromise","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"EventLoopPromise"}],"abstract":[{"type":"text","text":"A promise to provide a result later."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/EventLoopPromise","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EventLoopPromise"}],"url":"\/documentation\/nio\/eventlooppromise"},"doc://org.swift.docc/documentation/NIO":{"role":"collection","title":"NIO","abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO","kind":"symbol","type":"topic","url":"\/documentation\/nio"}}}