{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ByteToMessageDecoderError"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/nio\/bytetomessagedecodererror"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.swift.docc\/s5ErrorP","doc:\/\/org.swift.docc\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.swift.docc\/documentation\/NIO\/ByteToMessageDecoderError","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Common errors thrown by "},{"type":"codeVoice","code":"ByteToMessageDecoder"},{"type":"text","text":"s."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ByteToMessageDecoderError"}],"title":"ByteToMessageDecoderError","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"s:3NIO25ByteToMessageDecoderErrorO","modules":[{"name":"NIO"}],"navigatorTitle":[{"kind":"identifier","text":"ByteToMessageDecoderError"}]},"hierarchy":{"paths":[["doc:\/\/org.swift.docc\/documentation\/NIO"]]},"topicSections":[{"title":"Structures","identifiers":["doc:\/\/org.swift.docc\/documentation\/NIO\/ByteToMessageDecoderError\/PayloadTooLargeError"]},{"title":"Enumeration Cases","identifiers":["doc:\/\/org.swift.docc\/documentation\/NIO\/ByteToMessageDecoderError\/dataReceivedInErrorState(_:_:)","doc:\/\/org.swift.docc\/documentation\/NIO\/ByteToMessageDecoderError\/leftoverDataWhenDone(_:)"]}],"references":{"doc://org.swift.docc/documentation/NIO/ByteToMessageDecoderError/dataReceivedInErrorState(_:_:)":{"role":"symbol","title":"ByteToMessageDecoderError.dataReceivedInErrorState(_:_:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataReceivedInErrorState"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"ByteBuffer","preciseIdentifier":"s:3NIO10ByteBufferV"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"More data has been received by a "},{"type":"codeVoice","code":"ByteToMessageHandler"},{"type":"text","text":" despite the fact that an error has previously been"},{"type":"text","text":" "},{"type":"text","text":"emitted. The associated "},{"type":"codeVoice","code":"Error"},{"type":"text","text":" is the error previously emitted and the "},{"type":"codeVoice","code":"ByteBuffer"},{"type":"text","text":" is the extra data that has"},{"type":"text","text":" "},{"type":"text","text":"been received. The common cause for this error to be emitted is the user not having torn down the "},{"type":"codeVoice","code":"Channel"},{"type":"text","text":" "},{"type":"text","text":"after previously an "},{"type":"codeVoice","code":"Error"},{"type":"text","text":" has been sent through the pipeline using "},{"type":"codeVoice","code":"fireErrorCaught"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/ByteToMessageDecoderError\/dataReceivedInErrorState(_:_:)","kind":"symbol","type":"topic","url":"\/documentation\/nio\/bytetomessagedecodererror\/datareceivedinerrorstate(_:_:)"},"doc://org.swift.docc/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/org.swift.docc\/s8SendableP"},"doc://org.swift.docc/documentation/NIO/ByteToMessageDecoderError/leftoverDataWhenDone(_:)":{"role":"symbol","title":"ByteToMessageDecoderError.leftoverDataWhenDone(_:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftoverDataWhenDone"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ByteBuffer","preciseIdentifier":"s:3NIO10ByteBufferV"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This error can be thrown by "},{"type":"codeVoice","code":"ByteToMessageDecoder"},{"type":"text","text":"s if there was unexpectedly some left-over data when the"},{"type":"text","text":" "},{"type":"codeVoice","code":"ByteToMessageDecoder"},{"type":"text","text":" was removed from the pipeline or the "},{"type":"codeVoice","code":"Channel"},{"type":"text","text":" was closed."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/ByteToMessageDecoderError\/leftoverDataWhenDone(_:)","kind":"symbol","type":"topic","url":"\/documentation\/nio\/bytetomessagedecodererror\/leftoverdatawhendone(_:)"},"doc://org.swift.docc/documentation/NIO":{"role":"collection","title":"NIO","abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO","kind":"symbol","type":"topic","url":"\/documentation\/nio"},"doc://org.swift.docc/documentation/NIO/ByteToMessageDecoderError":{"role":"symbol","title":"ByteToMessageDecoderError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ByteToMessageDecoderError"}],"abstract":[{"type":"text","text":"Common errors thrown by "},{"type":"codeVoice","code":"ByteToMessageDecoder"},{"type":"text","text":"s."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/ByteToMessageDecoderError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ByteToMessageDecoderError"}],"url":"\/documentation\/nio\/bytetomessagedecodererror"},"doc://org.swift.docc/documentation/NIO/ByteToMessageDecoderError/PayloadTooLargeError":{"role":"symbol","title":"ByteToMessageDecoderError.PayloadTooLargeError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"PayloadTooLargeError"}],"abstract":[{"type":"text","text":"This error can be thrown by "},{"type":"codeVoice","code":"ByteToMessageDecoder"},{"type":"text","text":"s if the incoming payload is larger than the max specified."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/ByteToMessageDecoderError\/PayloadTooLargeError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PayloadTooLargeError"}],"url":"\/documentation\/nio\/bytetomessagedecodererror\/payloadtoolargeerror"},"doc://org.swift.docc/s5ErrorP":{"type":"unresolvable","title":"Swift.Error","identifier":"doc:\/\/org.swift.docc\/s5ErrorP"}}}