{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MachErrorCode"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/nio\/macherrorcode"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.swift.docc\/SQ","doc:\/\/org.swift.docc\/SH","doc:\/\/org.swift.docc\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Enumeration describing Mach error codes."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MachErrorCode"}],"title":"MachErrorCode","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@Darwin@E@MachErrorCode","modules":[{"name":"NIO"}],"navigatorTitle":[{"kind":"identifier","text":"MachErrorCode"}]},"hierarchy":{"paths":[["doc:\/\/org.swift.docc\/documentation\/NIO"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/aborted","doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/alreadyInSet","doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/alreadyWaiting","doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/codesignError","doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/defaultSet","doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/exceptionProtected","doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/failure","doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/invalidAddress","doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/invalidArgument","doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/invalidCapability","doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/invalidHost","doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/invalidLedger","doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/invalidMemoryControl","doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/invalidName","doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/invalidObject","doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/invalidPolicy","doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/invalidProcessorSet","doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/invalidRight","doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/invalidSecurity","doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/invalidTask","doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/invalidValue","doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/lockOwned","doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/lockOwnedSelf","doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/lockSetDestroyed","doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/lockUnstable","doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/memoryDataMoved","doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/memoryError","doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/memoryFailure","doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/memoryPresent","doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/memoryRestartCopy","doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/nameExists","doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/noAccess","doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/noSpace","doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/nodeDown","doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/notDepressed","doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/notInSet","doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/notReceiver","doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/notSupported","doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/notWaiting","doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/operationTimedOut","doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/policyLimit","doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/policyStatic","doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/protectionFailure","doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/resourceShortage","doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/rightExists","doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/rpcContinueOrphan","doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/rpcServerTerminated","doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/rpcTerminateOrphan","doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/semaphoreDestroyed","doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/success","doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/terminated","doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/userReferencesOverflow"]},{"title":"Initializers","identifiers":["doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/init(rawValue:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/rawValue-swift.property"]},{"title":"Type Aliases","identifiers":["doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/RawValue-swift.typealias"]}],"references":{"doc://org.swift.docc/documentation/NIO/MachErrorCode/codesignError":{"role":"symbol","title":"MachErrorCode.codesignError","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"codesignError"}],"abstract":[{"type":"text","text":"During a page fault, indicates that the page was rejected as a"},{"type":"text","text":" "},{"type":"text","text":"result of a signature check."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/codesignError","kind":"symbol","type":"topic","url":"\/documentation\/nio\/macherrorcode\/codesignerror"},"doc://org.swift.docc/documentation/NIO/MachErrorCode/resourceShortage":{"role":"symbol","title":"MachErrorCode.resourceShortage","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"resourceShortage"}],"abstract":[{"type":"text","text":"A system resource could not be allocated to fulfill this"},{"type":"text","text":" "},{"type":"text","text":"request.  This failure may not be permanent."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/resourceShortage","kind":"symbol","type":"topic","url":"\/documentation\/nio\/macherrorcode\/resourceshortage"},"doc://org.swift.docc/documentation/NIO/MachErrorCode/rpcServerTerminated":{"role":"symbol","title":"MachErrorCode.rpcServerTerminated","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rpcServerTerminated"}],"abstract":[{"type":"text","text":"Return from RPC indicating the target server was terminated"},{"type":"text","text":" "},{"type":"text","text":"before it successfully replied."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/rpcServerTerminated","kind":"symbol","type":"topic","url":"\/documentation\/nio\/macherrorcode\/rpcserverterminated"},"doc://org.swift.docc/documentation/NIO/MachErrorCode/aborted":{"role":"symbol","title":"MachErrorCode.aborted","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"aborted"}],"abstract":[{"type":"text","text":"The operation was aborted.  Ipc code will catch this and reflect"},{"type":"text","text":" "},{"type":"text","text":"it as a message error."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/aborted","kind":"symbol","type":"topic","url":"\/documentation\/nio\/macherrorcode\/aborted"},"doc://org.swift.docc/documentation/NIO/MachErrorCode/invalidPolicy":{"role":"symbol","title":"MachErrorCode.invalidPolicy","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidPolicy"}],"abstract":[{"type":"text","text":"The specified scheduling policy is not currently enabled for the"},{"type":"text","text":" "},{"type":"text","text":"processor set."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/invalidPolicy","kind":"symbol","type":"topic","url":"\/documentation\/nio\/macherrorcode\/invalidpolicy"},"doc://org.swift.docc/documentation/NIO/MachErrorCode/invalidMemoryControl":{"role":"symbol","title":"MachErrorCode.invalidMemoryControl","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidMemoryControl"}],"abstract":[{"type":"text","text":"The port was not a memory cache control port."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/invalidMemoryControl","kind":"symbol","type":"topic","url":"\/documentation\/nio\/macherrorcode\/invalidmemorycontrol"},"doc://org.swift.docc/documentation/NIO/MachErrorCode/success":{"role":"symbol","title":"MachErrorCode.success","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"success"}],"abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/success","kind":"symbol","type":"topic","url":"\/documentation\/nio\/macherrorcode\/success"},"doc://org.swift.docc/documentation/NIO/MachErrorCode/terminated":{"role":"symbol","title":"MachErrorCode.terminated","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"terminated"}],"abstract":[{"type":"text","text":"Object has been terminated and is no longer available."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/terminated","kind":"symbol","type":"topic","url":"\/documentation\/nio\/macherrorcode\/terminated"},"doc://org.swift.docc/documentation/NIO/MachErrorCode/invalidArgument":{"role":"symbol","title":"MachErrorCode.invalidArgument","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidArgument"}],"abstract":[{"type":"text","text":"The function requested was not applicable to this type of"},{"type":"text","text":" "},{"type":"text","text":"argument, or an argument is invalid."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/invalidArgument","kind":"symbol","type":"topic","url":"\/documentation\/nio\/macherrorcode\/invalidargument"},"doc://org.swift.docc/documentation/NIO/MachErrorCode/notDepressed":{"role":"symbol","title":"MachErrorCode.notDepressed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notDepressed"}],"abstract":[{"type":"text","text":"thread_depress_abort was called on a thread which was not"},{"type":"text","text":" "},{"type":"text","text":"currently depressed."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/notDepressed","kind":"symbol","type":"topic","url":"\/documentation\/nio\/macherrorcode\/notdepressed"},"doc://org.swift.docc/documentation/NIO/MachErrorCode/nameExists":{"role":"symbol","title":"MachErrorCode.nameExists","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"nameExists"}],"abstract":[{"type":"text","text":"The name already denotes a right in the task."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/nameExists","kind":"symbol","type":"topic","url":"\/documentation\/nio\/macherrorcode\/nameexists"},"doc://org.swift.docc/documentation/NIO/MachErrorCode/exceptionProtected":{"role":"symbol","title":"MachErrorCode.exceptionProtected","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"exceptionProtected"}],"abstract":[{"type":"text","text":"An attempt was made to fetch an exception port that is"},{"type":"text","text":" "},{"type":"text","text":"protected, or to abort a thread while processing a protected"},{"type":"text","text":" "},{"type":"text","text":"exception."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/exceptionProtected","kind":"symbol","type":"topic","url":"\/documentation\/nio\/macherrorcode\/exceptionprotected"},"doc://org.swift.docc/documentation/NIO/MachErrorCode/notSupported":{"role":"symbol","title":"MachErrorCode.notSupported","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notSupported"}],"abstract":[{"type":"text","text":"Empty thread activation (No thread linked to it)."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/notSupported","kind":"symbol","type":"topic","url":"\/documentation\/nio\/macherrorcode\/notsupported"},"doc://org.swift.docc/documentation/NIO/MachErrorCode/alreadyWaiting":{"role":"symbol","title":"MachErrorCode.alreadyWaiting","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"alreadyWaiting"}],"abstract":[{"type":"text","text":"A thread is attempting to wait for an event for which there is"},{"type":"text","text":" "},{"type":"text","text":"already a waiting thread."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/alreadyWaiting","kind":"symbol","type":"topic","url":"\/documentation\/nio\/macherrorcode\/alreadywaiting"},"doc://org.swift.docc/documentation/NIO/MachErrorCode/noSpace":{"role":"symbol","title":"MachErrorCode.noSpace","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noSpace"}],"abstract":[{"type":"text","text":"The address range specified is already in use, or no address"},{"type":"text","text":" "},{"type":"text","text":"range of the size specified could be found."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/noSpace","kind":"symbol","type":"topic","url":"\/documentation\/nio\/macherrorcode\/nospace"},"doc://org.swift.docc/documentation/NIO/MachErrorCode/invalidAddress":{"role":"symbol","title":"MachErrorCode.invalidAddress","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidAddress"}],"abstract":[{"type":"text","text":"Specified address is not currently valid."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/invalidAddress","kind":"symbol","type":"topic","url":"\/documentation\/nio\/macherrorcode\/invalidaddress"},"doc://org.swift.docc/documentation/NIO/MachErrorCode/alreadyInSet":{"role":"symbol","title":"MachErrorCode.alreadyInSet","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"alreadyInSet"}],"abstract":[{"type":"text","text":"The receive right is already a member of the portset."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/alreadyInSet","kind":"symbol","type":"topic","url":"\/documentation\/nio\/macherrorcode\/alreadyinset"},"doc://org.swift.docc/documentation/NIO/MachErrorCode/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/nio\/macherrorcode\/init(rawvalue:)"},"doc://org.swift.docc/documentation/NIO/MachErrorCode":{"role":"symbol","title":"MachErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MachErrorCode"}],"abstract":[{"type":"text","text":"Enumeration describing Mach error codes."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MachErrorCode"}],"url":"\/documentation\/nio\/macherrorcode"},"doc://org.swift.docc/documentation/NIO/MachErrorCode/lockSetDestroyed":{"role":"symbol","title":"MachErrorCode.lockSetDestroyed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"lockSetDestroyed"}],"abstract":[{"type":"text","text":"Lock set has been destroyed and is no longer available."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/lockSetDestroyed","kind":"symbol","type":"topic","url":"\/documentation\/nio\/macherrorcode\/locksetdestroyed"},"doc://org.swift.docc/documentation/NIO/MachErrorCode/invalidHost":{"role":"symbol","title":"MachErrorCode.invalidHost","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidHost"}],"abstract":[{"type":"text","text":"Target host isn’t actually a host."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/invalidHost","kind":"symbol","type":"topic","url":"\/documentation\/nio\/macherrorcode\/invalidhost"},"doc://org.swift.docc/documentation/NIO/MachErrorCode/invalidTask":{"role":"symbol","title":"MachErrorCode.invalidTask","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidTask"}],"abstract":[{"type":"text","text":"Target task isn’t an active task."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/invalidTask","kind":"symbol","type":"topic","url":"\/documentation\/nio\/macherrorcode\/invalidtask"},"doc://org.swift.docc/documentation/NIO/MachErrorCode/memoryRestartCopy":{"role":"symbol","title":"MachErrorCode.memoryRestartCopy","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"memoryRestartCopy"}],"abstract":[{"type":"text","text":"A strategic copy was attempted of an object upon which a quicker"},{"type":"text","text":" "},{"type":"text","text":"copy is now possible.  The caller should retry the copy using"},{"type":"text","text":" "},{"type":"text","text":"vm_object_copy_quickly. This error code is seen only by the"},{"type":"text","text":" "},{"type":"text","text":"kernel."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/memoryRestartCopy","kind":"symbol","type":"topic","url":"\/documentation\/nio\/macherrorcode\/memoryrestartcopy"},"doc://org.swift.docc/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.swift.docc\/SQ"},"doc://org.swift.docc/documentation/NIO/MachErrorCode/rpcTerminateOrphan":{"role":"symbol","title":"MachErrorCode.rpcTerminateOrphan","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rpcTerminateOrphan"}],"abstract":[{"type":"text","text":"Terminate an orphaned activation."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/rpcTerminateOrphan","kind":"symbol","type":"topic","url":"\/documentation\/nio\/macherrorcode\/rpcterminateorphan"},"doc://org.swift.docc/documentation/NIO/MachErrorCode/invalidName":{"role":"symbol","title":"MachErrorCode.invalidName","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidName"}],"abstract":[{"type":"text","text":"The name doesn’t denote a right in the task."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/invalidName","kind":"symbol","type":"topic","url":"\/documentation\/nio\/macherrorcode\/invalidname"},"doc://org.swift.docc/documentation/NIO/MachErrorCode/rpcContinueOrphan":{"role":"symbol","title":"MachErrorCode.rpcContinueOrphan","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rpcContinueOrphan"}],"abstract":[{"type":"text","text":"Allow an orphaned activation to continue executing."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/rpcContinueOrphan","kind":"symbol","type":"topic","url":"\/documentation\/nio\/macherrorcode\/rpccontinueorphan"},"doc://org.swift.docc/documentation/NIO/MachErrorCode/failure":{"role":"symbol","title":"MachErrorCode.failure","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failure"}],"abstract":[{"type":"text","text":"The function could not be performed.  A catch-all."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/failure","kind":"symbol","type":"topic","url":"\/documentation\/nio\/macherrorcode\/failure"},"doc://org.swift.docc/documentation/NIO/MachErrorCode/memoryDataMoved":{"role":"symbol","title":"MachErrorCode.memoryDataMoved","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"memoryDataMoved"}],"abstract":[{"type":"text","text":"A page was requested of a memory manager via"},{"type":"text","text":" "},{"type":"text","text":"memory_object_data_request for an object using a"},{"type":"text","text":" "},{"type":"text","text":"MEMORY_OBJECT_COPY_CALL strategy, with the VM_PROT_WANTS_COPY"},{"type":"text","text":" "},{"type":"text","text":"flag being used to specify that the page desired is for a copy"},{"type":"text","text":" "},{"type":"text","text":"of the object, and the memory manager has detected the page was"},{"type":"text","text":" "},{"type":"text","text":"pushed into a copy of the object while the kernel was walking"},{"type":"text","text":" "},{"type":"text","text":"the shadow chain from the copy to the object. This error code is"},{"type":"text","text":" "},{"type":"text","text":"delivered via memory_object_data_error and is handled by the"},{"type":"text","text":" "},{"type":"text","text":"kernel (it forces the kernel to restart the fault). It will not"},{"type":"text","text":" "},{"type":"text","text":"be seen by users."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/memoryDataMoved","kind":"symbol","type":"topic","url":"\/documentation\/nio\/macherrorcode\/memorydatamoved"},"doc://org.swift.docc/documentation/NIO/MachErrorCode/notInSet":{"role":"symbol","title":"MachErrorCode.notInSet","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notInSet"}],"abstract":[{"type":"text","text":"The receive right is not a member of a port set."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/notInSet","kind":"symbol","type":"topic","url":"\/documentation\/nio\/macherrorcode\/notinset"},"doc://org.swift.docc/documentation/NIO/MachErrorCode/semaphoreDestroyed":{"role":"symbol","title":"MachErrorCode.semaphoreDestroyed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"semaphoreDestroyed"}],"abstract":[{"type":"text","text":"Semaphore has been destroyed and is no longer available."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/semaphoreDestroyed","kind":"symbol","type":"topic","url":"\/documentation\/nio\/macherrorcode\/semaphoredestroyed"},"doc://org.swift.docc/documentation/NIO/MachErrorCode/defaultSet":{"role":"symbol","title":"MachErrorCode.defaultSet","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultSet"}],"abstract":[{"type":"text","text":"An attempt was made to destroy the default processor set."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/defaultSet","kind":"symbol","type":"topic","url":"\/documentation\/nio\/macherrorcode\/defaultset"},"doc://org.swift.docc/documentation/NIO/MachErrorCode/memoryError":{"role":"symbol","title":"MachErrorCode.memoryError","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"memoryError"}],"abstract":[{"type":"text","text":"During a page fault, the memory object indicated that the data"},{"type":"text","text":" "},{"type":"text","text":"could not be returned.  This failure may be temporary; future"},{"type":"text","text":" "},{"type":"text","text":"attempts to access this same data may succeed, as defined by the"},{"type":"text","text":" "},{"type":"text","text":"memory object."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/memoryError","kind":"symbol","type":"topic","url":"\/documentation\/nio\/macherrorcode\/memoryerror"},"doc://org.swift.docc/documentation/NIO/MachErrorCode/nodeDown":{"role":"symbol","title":"MachErrorCode.nodeDown","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"nodeDown"}],"abstract":[{"type":"text","text":"Remote node down or inaccessible."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/nodeDown","kind":"symbol","type":"topic","url":"\/documentation\/nio\/macherrorcode\/nodedown"},"doc://org.swift.docc/documentation/NIO/MachErrorCode/policyLimit":{"role":"symbol","title":"MachErrorCode.policyLimit","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"policyLimit"}],"abstract":[{"type":"text","text":"The specified scheduling attributes exceed the thread’s limits."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/policyLimit","kind":"symbol","type":"topic","url":"\/documentation\/nio\/macherrorcode\/policylimit"},"doc://org.swift.docc/documentation/NIO/MachErrorCode/lockOwned":{"role":"symbol","title":"MachErrorCode.lockOwned","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"lockOwned"}],"abstract":[{"type":"text","text":"The lock is already owned by another thread."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/lockOwned","kind":"symbol","type":"topic","url":"\/documentation\/nio\/macherrorcode\/lockowned"},"doc://org.swift.docc/documentation/NIO/MachErrorCode/notReceiver":{"role":"symbol","title":"MachErrorCode.notReceiver","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notReceiver"}],"abstract":[{"type":"text","text":"The task in question does not hold receive rights for the port"},{"type":"text","text":" "},{"type":"text","text":"argument."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/notReceiver","kind":"symbol","type":"topic","url":"\/documentation\/nio\/macherrorcode\/notreceiver"},"doc://org.swift.docc/documentation/NIO/MachErrorCode/rightExists":{"role":"symbol","title":"MachErrorCode.rightExists","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightExists"}],"abstract":[{"type":"text","text":"The task already has send or receive rights for the port under"},{"type":"text","text":" "},{"type":"text","text":"another name."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/rightExists","kind":"symbol","type":"topic","url":"\/documentation\/nio\/macherrorcode\/rightexists"},"doc://org.swift.docc/documentation/NIO/MachErrorCode/invalidSecurity":{"role":"symbol","title":"MachErrorCode.invalidSecurity","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidSecurity"}],"abstract":[{"type":"text","text":"An argument supplied to assert security privilege was not a host"},{"type":"text","text":" "},{"type":"text","text":"security port."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/invalidSecurity","kind":"symbol","type":"topic","url":"\/documentation\/nio\/macherrorcode\/invalidsecurity"},"doc://org.swift.docc/documentation/NIO/MachErrorCode/policyStatic":{"role":"symbol","title":"MachErrorCode.policyStatic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"policyStatic"}],"abstract":[{"type":"text","text":"The requested property cannot be changed at this time."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/policyStatic","kind":"symbol","type":"topic","url":"\/documentation\/nio\/macherrorcode\/policystatic"},"doc://org.swift.docc/documentation/NIO/MachErrorCode/operationTimedOut":{"role":"symbol","title":"MachErrorCode.operationTimedOut","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"operationTimedOut"}],"abstract":[{"type":"text","text":"Some thread-oriented operation (semaphore_wait) timed out."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/operationTimedOut","kind":"symbol","type":"topic","url":"\/documentation\/nio\/macherrorcode\/operationtimedout"},"doc://org.swift.docc/documentation/NIO/MachErrorCode/memoryFailure":{"role":"symbol","title":"MachErrorCode.memoryFailure","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"memoryFailure"}],"abstract":[{"type":"text","text":"During a page fault, the target address refers to a memory"},{"type":"text","text":" "},{"type":"text","text":"object that has been destroyed.  This failure is permanent."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/memoryFailure","kind":"symbol","type":"topic","url":"\/documentation\/nio\/macherrorcode\/memoryfailure"},"doc://org.swift.docc/documentation/NIO/MachErrorCode/userReferencesOverflow":{"role":"symbol","title":"MachErrorCode.userReferencesOverflow","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"userReferencesOverflow"}],"abstract":[{"type":"text","text":"Operation would overflow limit on user-references."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/userReferencesOverflow","kind":"symbol","type":"topic","url":"\/documentation\/nio\/macherrorcode\/userreferencesoverflow"},"doc://org.swift.docc/documentation/NIO/MachErrorCode/rawValue-swift.property":{"role":"symbol","title":"rawValue","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/rawValue-swift.property","kind":"symbol","type":"topic","url":"\/documentation\/nio\/macherrorcode\/rawvalue-swift.property"},"doc://org.swift.docc/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/org.swift.docc\/SY"},"doc://org.swift.docc/documentation/NIO/MachErrorCode/noAccess":{"role":"symbol","title":"MachErrorCode.noAccess","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noAccess"}],"abstract":[{"type":"text","text":"Bogus access restriction."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/noAccess","kind":"symbol","type":"topic","url":"\/documentation\/nio\/macherrorcode\/noaccess"},"doc://org.swift.docc/documentation/NIO/MachErrorCode/invalidProcessorSet":{"role":"symbol","title":"MachErrorCode.invalidProcessorSet","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidProcessorSet"}],"abstract":[{"type":"text","text":"An argument applied to assert processor set privilege was not a"},{"type":"text","text":" "},{"type":"text","text":"processor set control port."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/invalidProcessorSet","kind":"symbol","type":"topic","url":"\/documentation\/nio\/macherrorcode\/invalidprocessorset"},"doc://org.swift.docc/documentation/NIO/MachErrorCode/RawValue-swift.typealias":{"role":"symbol","title":"MachErrorCode.RawValue","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"RawValue"}],"abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/RawValue-swift.typealias","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RawValue"}],"url":"\/documentation\/nio\/macherrorcode\/rawvalue-swift.typealias"},"doc://org.swift.docc/documentation/NIO":{"role":"collection","title":"NIO","abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO","kind":"symbol","type":"topic","url":"\/documentation\/nio"},"doc://org.swift.docc/documentation/NIO/MachErrorCode/lockUnstable":{"role":"symbol","title":"MachErrorCode.lockUnstable","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"lockUnstable"}],"abstract":[{"type":"text","text":"The thread holding the lock terminated before releasing the lock."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/lockUnstable","kind":"symbol","type":"topic","url":"\/documentation\/nio\/macherrorcode\/lockunstable"},"doc://org.swift.docc/documentation/NIO/MachErrorCode/memoryPresent":{"role":"symbol","title":"MachErrorCode.memoryPresent","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"memoryPresent"}],"abstract":[{"type":"text","text":"An attempt was made to supply “precious” data for memory that is"},{"type":"text","text":" "},{"type":"text","text":"already present in a memory object."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/memoryPresent","kind":"symbol","type":"topic","url":"\/documentation\/nio\/macherrorcode\/memorypresent"},"doc://org.swift.docc/documentation/NIO/MachErrorCode/invalidCapability":{"role":"symbol","title":"MachErrorCode.invalidCapability","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidCapability"}],"abstract":[{"type":"text","text":"The supplied (port) capability is improper."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/invalidCapability","kind":"symbol","type":"topic","url":"\/documentation\/nio\/macherrorcode\/invalidcapability"},"doc://org.swift.docc/documentation/NIO/MachErrorCode/protectionFailure":{"role":"symbol","title":"MachErrorCode.protectionFailure","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"protectionFailure"}],"abstract":[{"type":"text","text":"Specified memory is valid, but does not permit the required"},{"type":"text","text":" "},{"type":"text","text":"forms of access."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/protectionFailure","kind":"symbol","type":"topic","url":"\/documentation\/nio\/macherrorcode\/protectionfailure"},"doc://org.swift.docc/documentation/NIO/MachErrorCode/lockOwnedSelf":{"role":"symbol","title":"MachErrorCode.lockOwnedSelf","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"lockOwnedSelf"}],"abstract":[{"type":"text","text":"The lock is already owned by the calling thread."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/lockOwnedSelf","kind":"symbol","type":"topic","url":"\/documentation\/nio\/macherrorcode\/lockownedself"},"doc://org.swift.docc/documentation/NIO/MachErrorCode/invalidValue":{"role":"symbol","title":"MachErrorCode.invalidValue","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidValue"}],"abstract":[{"type":"text","text":"A blatant range error."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/invalidValue","kind":"symbol","type":"topic","url":"\/documentation\/nio\/macherrorcode\/invalidvalue"},"doc://org.swift.docc/documentation/NIO/MachErrorCode/invalidObject":{"role":"symbol","title":"MachErrorCode.invalidObject","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidObject"}],"abstract":[{"type":"text","text":"The external memory manager failed to initialize the memory object."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/invalidObject","kind":"symbol","type":"topic","url":"\/documentation\/nio\/macherrorcode\/invalidobject"},"doc://org.swift.docc/documentation/NIO/MachErrorCode/invalidRight":{"role":"symbol","title":"MachErrorCode.invalidRight","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidRight"}],"abstract":[{"type":"text","text":"The name denotes a right, but not an appropriate right."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/invalidRight","kind":"symbol","type":"topic","url":"\/documentation\/nio\/macherrorcode\/invalidright"},"doc://org.swift.docc/documentation/NIO/MachErrorCode/invalidLedger":{"role":"symbol","title":"MachErrorCode.invalidLedger","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidLedger"}],"abstract":[{"type":"text","text":"A ledger was required but not supplied."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/invalidLedger","kind":"symbol","type":"topic","url":"\/documentation\/nio\/macherrorcode\/invalidledger"},"doc://org.swift.docc/documentation/NIO/MachErrorCode/notWaiting":{"role":"symbol","title":"MachErrorCode.notWaiting","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notWaiting"}],"abstract":[{"type":"text","text":"A signalled thread was not actually waiting."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/notWaiting","kind":"symbol","type":"topic","url":"\/documentation\/nio\/macherrorcode\/notwaiting"},"doc://org.swift.docc/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.swift.docc\/SH"}}}