{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NIOCloseOnErrorHandler"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/nio\/niocloseonerrorhandler"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.swift.docc\/documentation\/NIO\/ChannelHandler","doc:\/\/org.swift.docc\/documentation\/NIO\/ChannelInboundHandler"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.swift.docc\/documentation\/NIO\/NIOCloseOnErrorHandler","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"ChannelInboundHandler"},{"type":"text","text":" that closes the channel when an error is caught"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NIOCloseOnErrorHandler"}],"title":"NIOCloseOnErrorHandler","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"s:3NIO22NIOCloseOnErrorHandlerC","modules":[{"name":"NIO"}],"navigatorTitle":[{"kind":"identifier","text":"NIOCloseOnErrorHandler"}]},"hierarchy":{"paths":[["doc:\/\/org.swift.docc\/documentation\/NIO"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.swift.docc\/documentation\/NIO\/NIOCloseOnErrorHandler\/init()"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.swift.docc\/documentation\/NIO\/NIOCloseOnErrorHandler\/errorCaught(context:error:)"]},{"title":"Type Aliases","identifiers":["doc:\/\/org.swift.docc\/documentation\/NIO\/NIOCloseOnErrorHandler\/InboundIn"]},{"title":"Default Implementations","identifiers":["doc:\/\/org.swift.docc\/documentation\/NIO\/NIOCloseOnErrorHandler\/ChannelHandler-Implementations","doc:\/\/org.swift.docc\/documentation\/NIO\/NIOCloseOnErrorHandler\/ChannelInboundHandler-Implementations"],"generated":true}],"references":{"doc://org.swift.docc/documentation/NIO/ChannelInboundHandler":{"role":"symbol","title":"ChannelInboundHandler","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChannelInboundHandler"}],"abstract":[{"type":"codeVoice","code":"ChannelHandler"},{"type":"text","text":" which handles inbound I\/O events for a "},{"type":"codeVoice","code":"Channel"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/ChannelInboundHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChannelInboundHandler"}],"url":"\/documentation\/nio\/channelinboundhandler"},"doc://org.swift.docc/documentation/NIO/NIOCloseOnErrorHandler":{"role":"symbol","title":"NIOCloseOnErrorHandler","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NIOCloseOnErrorHandler"}],"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"ChannelInboundHandler"},{"type":"text","text":" that closes the channel when an error is caught"}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/NIOCloseOnErrorHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NIOCloseOnErrorHandler"}],"url":"\/documentation\/nio\/niocloseonerrorhandler"},"doc://org.swift.docc/documentation/NIO":{"role":"collection","title":"NIO","abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO","kind":"symbol","type":"topic","url":"\/documentation\/nio"},"doc://org.swift.docc/documentation/NIO/ChannelHandler":{"role":"symbol","title":"ChannelHandler","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChannelHandler"}],"abstract":[{"type":"text","text":"You should "},{"type":"emphasis","inlineContent":[{"type":"text","text":"never"}]},{"type":"text","text":" implement this protocol directly. Please implement one of its sub-protocols."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/ChannelHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChannelHandler"}],"url":"\/documentation\/nio\/channelhandler"},"doc://org.swift.docc/documentation/NIO/NIOCloseOnErrorHandler/errorCaught(context:error:)":{"role":"symbol","title":"errorCaught(context:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorCaught"},{"kind":"text","text":"("},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChannelHandlerContext","preciseIdentifier":"s:3NIO21ChannelHandlerContextC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"An error was encountered earlier in the inbound "},{"type":"codeVoice","code":"ChannelPipeline"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/NIOCloseOnErrorHandler\/errorCaught(context:error:)","kind":"symbol","type":"topic","url":"\/documentation\/nio\/niocloseonerrorhandler\/errorcaught(context:error:)"},"doc://org.swift.docc/documentation/NIO/NIOCloseOnErrorHandler/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Initialize a "},{"type":"codeVoice","code":"NIOCloseOnErrorHandler"}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/NIOCloseOnErrorHandler\/init()","kind":"symbol","type":"topic","url":"\/documentation\/nio\/niocloseonerrorhandler\/init()"},"doc://org.swift.docc/documentation/NIO/NIOCloseOnErrorHandler/ChannelHandler-Implementations":{"role":"collectionGroup","title":"ChannelHandler Implementations","abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/NIOCloseOnErrorHandler\/ChannelHandler-Implementations","kind":"article","type":"topic","url":"\/documentation\/nio\/niocloseonerrorhandler\/channelhandler-implementations"},"doc://org.swift.docc/documentation/NIO/NIOCloseOnErrorHandler/ChannelInboundHandler-Implementations":{"role":"collectionGroup","title":"ChannelInboundHandler Implementations","abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/NIOCloseOnErrorHandler\/ChannelInboundHandler-Implementations","kind":"article","type":"topic","url":"\/documentation\/nio\/niocloseonerrorhandler\/channelinboundhandler-implementations"},"doc://org.swift.docc/documentation/NIO/NIOCloseOnErrorHandler/InboundIn":{"role":"symbol","title":"NIOCloseOnErrorHandler.InboundIn","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"InboundIn"}],"abstract":[{"type":"text","text":"The type of the inbound data which is wrapped in "},{"type":"codeVoice","code":"NIOAny"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/NIOCloseOnErrorHandler\/InboundIn","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InboundIn"}],"url":"\/documentation\/nio\/niocloseonerrorhandler\/inboundin"}}}