{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SingleConnectionFailure"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/nio\/singleconnectionfailure"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.swift.docc\/documentation\/NIO\/SingleConnectionFailure","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An error that occurred during connection to a given target."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SingleConnectionFailure"}],"title":"SingleConnectionFailure","roleHeading":"Structure","role":"symbol","symbolKind":"struct","externalID":"s:3NIO23SingleConnectionFailureV","modules":[{"name":"NIO"}],"navigatorTitle":[{"kind":"identifier","text":"SingleConnectionFailure"}]},"hierarchy":{"paths":[["doc:\/\/org.swift.docc\/documentation\/NIO"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/org.swift.docc\/documentation\/NIO\/SingleConnectionFailure\/error","doc:\/\/org.swift.docc\/documentation\/NIO\/SingleConnectionFailure\/target"]}],"references":{"doc://org.swift.docc/documentation/NIO/SingleConnectionFailure":{"role":"symbol","title":"SingleConnectionFailure","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SingleConnectionFailure"}],"abstract":[{"type":"text","text":"An error that occurred during connection to a given target."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/SingleConnectionFailure","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SingleConnectionFailure"}],"url":"\/documentation\/nio\/singleconnectionfailure"},"doc://org.swift.docc/documentation/NIO/SingleConnectionFailure/error":{"role":"symbol","title":"error","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"}],"abstract":[{"type":"text","text":"The error we encountered."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/SingleConnectionFailure\/error","kind":"symbol","type":"topic","url":"\/documentation\/nio\/singleconnectionfailure\/error"},"doc://org.swift.docc/documentation/NIO/SingleConnectionFailure/target":{"role":"symbol","title":"target","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"target"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SocketAddress","preciseIdentifier":"s:3NIO13SocketAddressO"}],"abstract":[{"type":"text","text":"The target we were trying to connect to when we encountered the error."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/SingleConnectionFailure\/target","kind":"symbol","type":"topic","url":"\/documentation\/nio\/singleconnectionfailure\/target"},"doc://org.swift.docc/documentation/NIO":{"role":"collection","title":"NIO","abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO","kind":"symbol","type":"topic","url":"\/documentation\/nio"}}}