{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"x86_exception_state"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/nio\/x86_exception_state-swift.struct"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.swift.docc\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.swift.docc\/documentation\/NIO\/x86_exception_state-swift.struct","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.swift.docc\/documentation\/NIO\/x86_exception_state-swift.struct\/init()","doc:\/\/org.swift.docc\/documentation\/NIO\/x86_exception_state-swift.struct\/init(esh:ues:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.swift.docc\/documentation\/NIO\/x86_exception_state-swift.struct\/esh","doc:\/\/org.swift.docc\/documentation\/NIO\/x86_exception_state-swift.struct\/ues"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"x86_exception_state"}],"title":"x86_exception_state","roleHeading":"Structure","role":"symbol","symbolKind":"struct","externalID":"c:@S@x86_exception_state","modules":[{"name":"NIO"}],"navigatorTitle":[{"kind":"identifier","text":"x86_exception_state"}]},"hierarchy":{"paths":[["doc:\/\/org.swift.docc\/documentation\/NIO"]]},"references":{"doc://org.swift.docc/documentation/NIO":{"role":"collection","title":"NIO","abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO","kind":"symbol","type":"topic","url":"\/documentation\/nio"},"doc://org.swift.docc/documentation/NIO/x86_exception_state-swift.struct/init(esh:ues:)":{"role":"symbol","title":"init(esh:ues:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"esh"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"x86_state_hdr_t","preciseIdentifier":"c:@T@x86_state_hdr_t"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ues"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"x86_exception_state","preciseIdentifier":"c:@S@x86_exception_state"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"__Unnamed_union_ues"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/x86_exception_state-swift.struct\/init(esh:ues:)","kind":"symbol","type":"topic","url":"\/documentation\/nio\/x86_exception_state-swift.struct\/init(esh:ues:)"},"doc://org.swift.docc/documentation/NIO/x86_exception_state-swift.struct/ues":{"role":"symbol","title":"ues","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ues"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"x86_exception_state","preciseIdentifier":"c:@S@x86_exception_state"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"__Unnamed_union_ues"}],"abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/x86_exception_state-swift.struct\/ues","kind":"symbol","type":"topic","url":"\/documentation\/nio\/x86_exception_state-swift.struct\/ues"},"doc://org.swift.docc/documentation/NIO/x86_exception_state-swift.struct":{"role":"symbol","title":"x86_exception_state","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"x86_exception_state"}],"abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/x86_exception_state-swift.struct","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"x86_exception_state"}],"url":"\/documentation\/nio\/x86_exception_state-swift.struct"},"doc://org.swift.docc/documentation/NIO/x86_exception_state-swift.struct/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/x86_exception_state-swift.struct\/init()","kind":"symbol","type":"topic","url":"\/documentation\/nio\/x86_exception_state-swift.struct\/init()"},"doc://org.swift.docc/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/org.swift.docc\/s8SendableP"},"doc://org.swift.docc/documentation/NIO/x86_exception_state-swift.struct/esh":{"role":"symbol","title":"esh","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"esh"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"x86_state_hdr_t","preciseIdentifier":"c:@T@x86_state_hdr_t"}],"abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/x86_exception_state-swift.struct\/esh","kind":"symbol","type":"topic","url":"\/documentation\/nio\/x86_exception_state-swift.struct\/esh"}}}