{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ExitCode"}],"languages":["swift"],"platforms":["macOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"If youâ€™re printing custom errors messages yourself, you can throw this error"},{"type":"text","text":" "},{"type":"text","text":"to specify the exit code without adding any additional output to standard"},{"type":"text","text":" "},{"type":"text","text":"out or standard error."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/argumentparser\/exitcode"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.swift.docc\/SQ","doc:\/\/org.swift.docc\/s5ErrorP","doc:\/\/org.swift.docc\/SH","doc:\/\/org.swift.docc\/SY","doc:\/\/org.swift.docc\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.swift.docc\/documentation\/ArgumentParser\/ExitCode","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An error type that only includes an exit code."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ExitCode"}],"title":"ExitCode","roleHeading":"Structure","role":"symbol","symbolKind":"struct","externalID":"s:14ArgumentParser8ExitCodeV","modules":[{"name":"ArgumentParser"}],"navigatorTitle":[{"kind":"identifier","text":"ExitCode"}]},"hierarchy":{"paths":[["doc:\/\/org.swift.docc\/documentation\/ArgumentParser"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.swift.docc\/documentation\/ArgumentParser\/ExitCode\/init(_:)","doc:\/\/org.swift.docc\/documentation\/ArgumentParser\/ExitCode\/init(rawValue:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.swift.docc\/documentation\/ArgumentParser\/ExitCode\/isSuccess","doc:\/\/org.swift.docc\/documentation\/ArgumentParser\/ExitCode\/rawValue"]},{"title":"Type Properties","identifiers":["doc:\/\/org.swift.docc\/documentation\/ArgumentParser\/ExitCode\/failure","doc:\/\/org.swift.docc\/documentation\/ArgumentParser\/ExitCode\/success","doc:\/\/org.swift.docc\/documentation\/ArgumentParser\/ExitCode\/validationFailure"]},{"title":"Default Implementations","identifiers":["doc:\/\/org.swift.docc\/documentation\/ArgumentParser\/ExitCode\/Equatable-Implementations","doc:\/\/org.swift.docc\/documentation\/ArgumentParser\/ExitCode\/Error-Implementations","doc:\/\/org.swift.docc\/documentation\/ArgumentParser\/ExitCode\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://org.swift.docc/documentation/ArgumentParser/ExitCode/success":{"role":"symbol","title":"success","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"success"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ExitCode","preciseIdentifier":"s:14ArgumentParser8ExitCodeV"}],"abstract":[{"type":"text","text":"An exit code that indicates successful completion of a command."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/ArgumentParser\/ExitCode\/success","kind":"symbol","type":"topic","url":"\/documentation\/argumentparser\/exitcode\/success"},"doc://org.swift.docc/documentation/ArgumentParser":{"role":"collection","title":"ArgumentParser","abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/ArgumentParser","kind":"symbol","type":"topic","url":"\/documentation\/argumentparser"},"doc://org.swift.docc/documentation/ArgumentParser/ExitCode/Error-Implementations":{"role":"collectionGroup","title":"Error Implementations","abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/ArgumentParser\/ExitCode\/Error-Implementations","kind":"article","type":"topic","url":"\/documentation\/argumentparser\/exitcode\/error-implementations"},"doc://org.swift.docc/documentation/ArgumentParser/ExitCode/validationFailure":{"role":"symbol","title":"validationFailure","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"validationFailure"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ExitCode","preciseIdentifier":"s:14ArgumentParser8ExitCodeV"}],"abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/ArgumentParser\/ExitCode\/validationFailure","kind":"symbol","type":"topic","url":"\/documentation\/argumentparser\/exitcode\/validationfailure"},"doc://org.swift.docc/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.swift.docc\/SH"},"doc://org.swift.docc/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/org.swift.docc\/s8SendableP"},"doc://org.swift.docc/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.swift.docc\/SQ"},"doc://org.swift.docc/documentation/ArgumentParser/ExitCode":{"role":"symbol","title":"ExitCode","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ExitCode"}],"abstract":[{"type":"text","text":"An error type that only includes an exit code."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/ArgumentParser\/ExitCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ExitCode"}],"url":"\/documentation\/argumentparser\/exitcode"},"doc://org.swift.docc/s5ErrorP":{"type":"unresolvable","title":"Swift.Error","identifier":"doc:\/\/org.swift.docc\/s5ErrorP"},"doc://org.swift.docc/documentation/ArgumentParser/ExitCode/rawValue":{"role":"symbol","title":"rawValue","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"The exit code represented by this instance."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/ArgumentParser\/ExitCode\/rawValue","kind":"symbol","type":"topic","url":"\/documentation\/argumentparser\/exitcode\/rawvalue"},"doc://org.swift.docc/documentation/ArgumentParser/ExitCode/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/ArgumentParser\/ExitCode\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/argumentparser\/exitcode\/rawrepresentable-implementations"},"doc://org.swift.docc/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/org.swift.docc\/SY"},"doc://org.swift.docc/documentation/ArgumentParser/ExitCode/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/ArgumentParser\/ExitCode\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/argumentparser\/exitcode\/equatable-implementations"},"doc://org.swift.docc/documentation/ArgumentParser/ExitCode/isSuccess":{"role":"symbol","title":"isSuccess","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSuccess"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"A Boolean value indicating whether this exit code represents the"},{"type":"text","text":" "},{"type":"text","text":"successful completion of a command."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/ArgumentParser\/ExitCode\/isSuccess","kind":"symbol","type":"topic","url":"\/documentation\/argumentparser\/exitcode\/issuccess"},"doc://org.swift.docc/documentation/ArgumentParser/ExitCode/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/ArgumentParser\/ExitCode\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/argumentparser\/exitcode\/init(rawvalue:)"},"doc://org.swift.docc/documentation/ArgumentParser/ExitCode/init(_:)":{"role":"symbol","title":"init(_:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Creates a new "},{"type":"codeVoice","code":"ExitCode"},{"type":"text","text":" with the given code."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/ArgumentParser\/ExitCode\/init(_:)","kind":"symbol","type":"topic","url":"\/documentation\/argumentparser\/exitcode\/init(_:)"},"doc://org.swift.docc/documentation/ArgumentParser/ExitCode/failure":{"role":"symbol","title":"failure","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"failure"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ExitCode","preciseIdentifier":"s:14ArgumentParser8ExitCodeV"}],"abstract":[{"type":"text","text":"An exit code that indicates that the command failed."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/ArgumentParser\/ExitCode\/failure","kind":"symbol","type":"topic","url":"\/documentation\/argumentparser\/exitcode\/failure"}}}