{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorMessage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/swiftdocc\/outofprocessreferenceresolver\/response\/errormessage(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.swift.docc\/documentation\/SwiftDocC\/OutOfProcessReferenceResolver\/Response\/errorMessage(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The error message of the problem that the external link resolver encountered while resolving the requested topic or symbol."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorMessage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"OutOfProcessReferenceResolver.Response.errorMessage(_:)","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"s:9SwiftDocC29OutOfProcessReferenceResolverC8ResponseO12errorMessageyAESScAEmF","modules":[{"name":"SwiftDocC"}]},"hierarchy":{"paths":[["doc:\/\/org.swift.docc\/documentation\/SwiftDocC","doc:\/\/org.swift.docc\/documentation\/SwiftDocC\/OutOfProcessReferenceResolver","doc:\/\/org.swift.docc\/documentation\/SwiftDocC\/OutOfProcessReferenceResolver\/Response"]]},"references":{"doc://org.swift.docc/documentation/SwiftDocC/OutOfProcessReferenceResolver/Response":{"role":"symbol","title":"OutOfProcessReferenceResolver.Response","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Response"}],"abstract":[{"type":"text","text":"A response message from the external link resolver."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/SwiftDocC\/OutOfProcessReferenceResolver\/Response","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Response"}],"url":"\/documentation\/swiftdocc\/outofprocessreferenceresolver\/response"},"doc://org.swift.docc/documentation/SwiftDocC":{"role":"collection","title":"SwiftDocC","abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/SwiftDocC","kind":"symbol","type":"topic","url":"\/documentation\/swiftdocc"},"doc://org.swift.docc/documentation/SwiftDocC/OutOfProcessReferenceResolver":{"role":"symbol","title":"OutOfProcessReferenceResolver","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OutOfProcessReferenceResolver"}],"abstract":[{"type":"text","text":"A reference resolver that launches and interactively communicates with another process or service to resolve links."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/SwiftDocC\/OutOfProcessReferenceResolver","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OutOfProcessReferenceResolver"}],"url":"\/documentation\/swiftdocc\/outofprocessreferenceresolver"},"doc://org.swift.docc/documentation/SwiftDocC/OutOfProcessReferenceResolver/Response/errorMessage(_:)":{"role":"symbol","title":"OutOfProcessReferenceResolver.Response.errorMessage(_:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorMessage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"The error message of the problem that the external link resolver encountered while resolving the requested topic or symbol."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/SwiftDocC\/OutOfProcessReferenceResolver\/Response\/errorMessage(_:)","kind":"symbol","type":"topic","url":"\/documentation\/swiftdocc\/outofprocessreferenceresolver\/response\/errormessage(_:)"}}}